### ISSUE TITLE
Add support for DECIMAL type

### ISSUE THREAD

**Issue by fiorix** [prestodb/presto-go-client#13]
Add support for fixed-precision type: https://prestodb.io/docs/current/language/types.html#fixed-precision

**Comment by fiorix** [comment]
While looking at this I learned that Presto returns decimal types as literal strings. Perhaps this is why #11 and #12 wanted to implement this as strings.

I believe the right thing to do is to support decimals as `float64` and `sql.NullFloat64`.

**Comment by electrum** [comment]
What does the PostgreSQL driver return?

**Comment by fiorix** [comment]
github.com/lib/pq supports scanning decimals to `string`, `float64`, and their variants `sql.NullString` and `sql.NullFloat64`. Despite not being able to convert to `int64` for obvious reasons, a `CAST(NULL to DECIMAL(10,2))` can be scanned to `sql.NullInt64`.

I haven't tried github.com/go-sql-driver/mysql but I believe it should be consistent with pq.

That said, we should probably do the same here.

**Comment by fiorix** [comment]
This is a simple fix. Added a suggestion in https://github.com/prestodb/presto-go-client/pull/11#issuecomment-354118401 which should provide the same behavior as pq.
