### ISSUE TITLE
The Source Should have a default value,just like the presto-python-client

### ISSUE THREAD

**Issue by armsword** [prestodb/presto-go-client#16]
When my user use the presto-go-client to query the presto,the Source is null. And When I use the presto-python-client, the Source value is presto-python-client. I think the Source should have a default value and do not should be null. Because if the default Source value is not null ,the presto maintainer will be more easier to manage the queries.

The following picture shows the question:

![qq 20171228190017](https://user-images.githubusercontent.com/4738595/34408950-c8ebd6ca-ec01-11e7-8597-b47ae3c088d2.jpg)

**Comment by fiorix** [comment]
Makes sense. I will make it presto-go-client by default.

Worth mentioning that ideally the `source` field shouldn't be the value of which client library you're using to query presto. Instead, it's normally better to use a unique identifier for your program, e.g. the name of your program, or the absolute path of your binary.

**Comment by armsword** [comment]
@fiorix  Thanks. Currently, I  have a better solution to solve the user management. I use the resource group user name to identify  the user. The Source name can help me to position problem quickly.
