### ISSUE TITLE
Migrate to v2 client protocol

### ISSUE THREAD

**Issue by JavierZunzunegui** [prestodb/presto-go-client#30]
https://github.com/prestodb/presto/wiki/Presto-v2-client-protocol

**Comment by fiorix** [comment]
cc @electrum for visibility

**Comment by electrum** [comment]
That wiki page is a draft. The protocol specification is not final nor even checked in yet.

**Comment by electrum** [comment]
I’m going to close this for now. We will work with you once the protocol is stable and we are ready for clients to implement it.

**Comment by fiorix** [comment]
@electrum maybe drop a note in that page clarifying it's a draft
