### ISSUE TITLE
Add support for Presto warnings

### ISSUE THREAD

**Issue by ggreg** [prestodb/presto-go-client#42]
Presto now may returns a list of [warnings](https://github.com/prestodb/presto/blob/master/presto-spi/src/main/java/com/facebook/presto/spi/PrestoWarning.java) in the *warnings* field of the JSON struct returned by then coordinator when the client polls the status of a query.

The warning are useful to surface issues in queries at runtime.

**Comment by fiorix** [comment]
How do other clients consume these warning messages?

Since the Go client implements the standard database/sql interface, it doesn't leave many choices for users to receive this message as part of their query results.

We'd have to find a way to pass them back to users somehow.

**Comment by elonazoulay** [comment]
Some examples are the jdbc and presto-cli. The jdbc driver has a standard method getWarnings() which is part of the interface and presto-cli displays warnings on stderr.

Both use the presto-client which as @ggreg mentioned has a "warnings" field with a list of warnings.

**Comment by fiorix** [comment]
Given that we don't actually have a proper solution this, going to close the task until there's a PR that can be reviewed.
