### ISSUE TITLE
query result is not correct

### ISSUE THREAD

**Issue by armsword** [prestodb/presto-go-client#45]
SQL：
select id from table where year = '2019'  and month = '08'  and day = '05' and id = 360287970235245893 limit 1;

but the result is:
360287970235245888

The id in table is bigint type.

**Comment by adamgreenhall** [comment]
this appears to be an general problem with parsing bigint. you can see this issue via this test:
https://github.com/prestodb/presto-go-client/pull/46

**Comment by fiorix** [comment]
Merged. Thank you!
