### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by itshicheng** [prestodb/presto-go-client#48]
how to free memory  shared, waiting for help
![image](https://user-images.githubusercontent.com/13670704/67457530-803ba380-f666-11e9-8e4b-4af81047054c.png)

go tool pprof -alloc_space http://xxxxx:8899/debug/pprof/heap

![image](https://user-images.githubusercontent.com/13670704/67457395-1de2a300-f666-11e9-8a6d-0ee36c9b34f3.png)

package main

import (
	"database/sql"
	"fmt"
	_ "github.com/prestodb/presto-go-client/presto"
	"net/http"
	_ "net/http/pprof"
	"time"
)

var SerNum int

func ServerNum(app string, dt time.Time) int {

	dsn := "http://root@xxxxx:8080?catalog=hive&schema=tds_tmp"
	db, err := sql.Open("presto", dsn)
	if err != nil {
		fmt.Println(err)
	}
	defer db.Close()

	s := fmt.Sprintf(
		`select  count(ip) from xxx where dt='%s' and  appname='%s'`, dt.Format("20060102"), app)

	err = db.QueryRow(s).Scan(&SerNum)

	if err != nil {
		fmt.Println(err)
	} else {
		return SerNum
	}

	return 0
}

func main() {

	go func() {
		_ = http.ListenAndServe("0.0.0.0:8899", nil)
	}()

	for i := 0; i < 1000; i++ {
		num := ServerNum("xxx", time.Now())
		fmt.Println(num)
	}

}

**Comment by fiorix** [comment]
Cannot spend time troubleshooting this now. If you find something and send a PR we can review.
