### ISSUE TITLE
Support Basic Authentication

### ISSUE THREAD

**Issue by leowmjw** [prestodb/presto-go-client#8]
Support Basic Authentication when the Presto end-point is configured for LDAP Authentication.

**Comment by fiorix** [comment]
I think we can do this by accepting a password in the DSN, and anytime that a password is set we configure basic auth on outgoing requests to presto.

Today's DSN format is this:

```http[s]://user@host[:port][?parameters]```

Could be changed to this:

```http[s]://user[:password]@host[:port][?parameters]```

Happy to review PRs or eventually do this ourselves when time permits. Let us know if you have any plans to contribute this change.
